### ISSUE TITLE
Good to find the code again.

### ISSUE THREAD

**Issue by aunxx** [HomeworldSDL/HomeworldSDL#1]
Hi,
I'm pleased to find the code survives beyond the old defunct SVN repository.
Thought I'd recompile and play through for old times sake, and see what changes have been made since I worked on it many years ago. 
Aunxx

**Comment by andrewzirkel** [comment]
Good to see you.  How far did you get?  There is an issue in the research station level, guess I should create an issue for it.

**Comment by andrewzirkel** [comment]
I did fix the crash in super nova station level.
